In [2]:
import numpy as np
import torch
torch.__version__

'2.1.1+cu118'

In [3]:
x = torch.empty(5,3)
x

tensor([[-1.9542e-03,  1.5653e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
x = torch.rand(5,3)
print(x)
print(x.view(15))
x[:,1]

tensor([[0.7316, 0.3156, 0.8923],
        [0.9144, 0.2593, 0.6878],
        [0.9796, 0.1462, 0.5481],
        [0.3881, 0.2552, 0.6937],
        [0.6782, 0.3407, 0.6858]])
tensor([0.7316, 0.3156, 0.8923, 0.9144, 0.2593, 0.6878, 0.9796, 0.1462, 0.5481,
        0.3881, 0.2552, 0.6937, 0.6782, 0.3407, 0.6858])


tensor([0.3156, 0.2593, 0.1462, 0.2552, 0.3407])

In [5]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x.size()

torch.Size([2])

In [8]:
# 构造数据
import numpy as np
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1,1)
x_train.shape

(11, 1)

In [9]:
y_values = [2*i+1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1,1)
y_train.shape

(11, 1)

In [3]:
# 线性回归
import torch
import torch.nn as nn
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [4]:
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

In [5]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [6]:
# 指定好参数和损失函数
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

In [11]:
for epoch in range(epochs):
    epoch+=1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 50, loss 0.15812626481056213
epoch 100, loss 0.0901893898844719
epoch 150, loss 0.051440540701150894
epoch 200, loss 0.02933984249830246
epoch 250, loss 0.016734300181269646
epoch 300, loss 0.009544599801301956
epoch 350, loss 0.00544386962428689
epoch 400, loss 0.003104971954599023
epoch 450, loss 0.0017709416570141912
epoch 500, loss 0.0010100803337991238
epoch 550, loss 0.0005761130014434457
epoch 600, loss 0.00032858949271030724
epoch 650, loss 0.00018741973326541483
epoch 700, loss 0.00010690316412365064
epoch 750, loss 6.0971829952904955e-05
epoch 800, loss 3.4775526728481054e-05
epoch 850, loss 1.9834946215269156e-05
epoch 900, loss 1.1313770301057957e-05
epoch 950, loss 6.454070899053477e-06
epoch 1000, loss 3.6797093798668357e-06


In [16]:
# 模型测试
predicted = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
predicted

array([[ 0.99643135],
       [ 2.9969454 ],
       [ 4.9974594 ],
       [ 6.9979734 ],
       [ 8.998487  ],
       [10.9990015 ],
       [12.999516  ],
       [15.00003   ],
       [17.000544  ],
       [19.001059  ],
       [21.001572  ]], dtype=float32)

In [17]:
# 模型保存
torch.save(model.state_dict(), 'model.pkl')

In [18]:
# 模型读取
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

In [20]:
# gpu

input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

device = torch.device("cuda")

model.to(device)

epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

for epoch in range(epochs):
    epoch+=[-[]]
    inputs = torch.from_numpy(x_train).to(device)
    labels = torch.from_numpy(y_train).to(device)
    
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 50, loss 0.007088463753461838
epoch 100, loss 0.004042974207550287
epoch 150, loss 0.002305977512151003
epoch 200, loss 0.001315246568992734
epoch 250, loss 0.0007501689251512289
epoch 300, loss 0.00042786437552422285
epoch 350, loss 0.00024403280986007303
epoch 400, loss 0.0001391867408528924
epoch 450, loss 7.938464841572568e-05
epoch 500, loss 4.5275326556293294e-05
epoch 550, loss 2.5822311727097258e-05
epoch 600, loss 1.472541771363467e-05
epoch 650, loss 8.399444595852401e-06
epoch 700, loss 4.7903531594784e-06
epoch 750, loss 2.732280790951336e-06
epoch 800, loss 1.5585350183755509e-06
epoch 850, loss 8.889595051186916e-07
epoch 900, loss 5.068831683274766e-07
epoch 950, loss 2.8901928317282e-07
epoch 1000, loss 1.649623584398796e-07
