In [2]:
import torch
torch.__version__

'2.1.1+cu118'

In [3]:
x = torch.empty(5,3)
x

tensor([[-1.9542e-03,  1.5653e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
x = torch.rand(5,3)
print(x)
print(x.view(15))
x[:,1]

tensor([[0.7316, 0.3156, 0.8923],
        [0.9144, 0.2593, 0.6878],
        [0.9796, 0.1462, 0.5481],
        [0.3881, 0.2552, 0.6937],
        [0.6782, 0.3407, 0.6858]])
tensor([0.7316, 0.3156, 0.8923, 0.9144, 0.2593, 0.6878, 0.9796, 0.1462, 0.5481,
        0.3881, 0.2552, 0.6937, 0.6782, 0.3407, 0.6858])


tensor([0.3156, 0.2593, 0.1462, 0.2552, 0.3407])

In [5]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x.size()

torch.Size([2])